SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libJSON libUtils libIOInterface 

EXECUTABLE=jsonGen
MODE=CPP
CPP_TAGS_FILE=dev_tools_binaries-jsonGen-c++.tags
USE_JSON=YES

include ../../../../makefile.include
