EXPORT_INCLUDES=$(shell echo *.h)
SOURCES=$(shell echo *.cpp)

ADDITIONAL_INCLUDE_FLAGS+=$(PROJECT_ROOT_DIR)/DEV_TOOLS/EXTERNAL_INCLUDES/BOOST/tokenizer/include
TARGET_LIB=libString
TAGS_FILE=dev_tools_libraries_strings-c++.tags
LINKED_LIBS=libUtils libIOInterface

MODE=CPP

include ../makefiles_libaries.include
