SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libUtils libIOInterface 

EXECUTABLE=compareTwo
MODE=CPP
CPP_TAGS_FILE=dev_tools_binaries-compare-two-speed-c++.tags
USE_JSON=YES

include ../../../../makefile.include
