LINKED_LIBS= libPlot \
             libMath \
             libUtils\
			 libIOInterface\
			 libTest

BUILD_TIME_TESTS= plot 
CPP_TAGS_FILE=COMPSOC_Tests_PLOT.tags
USE_PLPLOT=YES

CORE_SIZE=unlimited

MODE=CPP
NO_TRAVIS=YES


include ../makefile_tests.include
