LINKED_LIBS= libUtils  \
			 libIOInterface \
			 libTest \
			 libString
 
BUILD_TIME_TESTS=binaryData time search dynStruct
CPP_TAGS_FILE=utilTests-c++.tags

BOOST_MODULES+=filesystem system

include ../makefile_tests.include
