LINKED_LIBS= libUtils  \
			 libIOInterface \
			 libTest \
			 libString
 
BUILD_TIME_TESTS=os binaryData time search dynStruct enum
CPP_TAGS_FILE=utilTests-c++.tags

BOOST_MODULES+=filesystem system regex

USE_BOOST=YES

include ../makefile_tests.include

export PROJET_ROOT_DIR

