LINKED_LIBS= libString\
             libIOInterface\
             libUtils\
			 libTest

BUILD_TIME_TESTS=tokens stringUtils
CPP_TAGS_FILE=dev_tools_test_strings-c++.tags
MODE=CPP

include ../makefile_tests.include
