LINKED_LIBS= libMath \
             libIOInterface\
             libUtils\
			 libTest

BUILD_TIME_TESTS=set sets pairs comb
CPP_TAGS_FILE=eulers_tesst_set-c++.tags
MODE=CPP

USE_GSL=YES

include ../makefile_tests.include
