EXPORT_INCLUDES=$(shell echo *.hpp *.h)
SOURCES=$(shell echo *.cpp)

TARGET_LIB=libCommands
LINKED_LIBS=libMeta libString libUtils libIOInterface
TAGS_FILE=dev_tools_libraries_libMeta-c++.tags

MODE=CPP

include ../makefiles_libaries.include
