EXPORT_INCLUDES=$(shell echo *.h)
SOURCES=$(shell echo *.cpp)

TAGS_FILE=dev_tools_lib_math_libCombination-c++.tags

USE_GSL=YES
USE_LOCAL_GSL=NO
MODE=CPP
LINKED_LIBS=libUtils libIOInterface

include ../makefile.libMath.include
