LINKED_LIBS= libThreadComms \
             libIOInterface\
             libUtils\
			 libTest

BUILD_TIME_TESTS=pipe
CPP_TAGS_FILE=dev_tools_cpp_tests_thread-comms-c++.tags
MODE=CPP

USE_BOOST=YES
USE_THREADS=YES

include ../makefile_tests.include
