LINKED_LIBS= libUtils  \
			 libIOInterface \
			 libTest \
			 libThread

BUILD_TIME_TESTS=dataVectorTest binaryReaderTests binaryWriterTests 
CPP_TAGS_FILE=testIOInterface-c++.tags
FATAL_WARNINGS=YES

include ../makefile_tests.include
