EXPORT_INCLUDES=$(shell echo *.h )
SOURCES=$(shell echo *.cpp)

TARGET_LIB=libCEF

LINKED_LIBS=libUtils libIOInterface
USE_CEF=YES
USE_GTK=YES

MODE=CPP
TAGS_FILE=DEV_TOOLS_CEF_c++.tags


include ../../../../makefile.include
