EXPORT_INCLUDES=$(shell echo *.h)
SOURCES=$(shell echo *.cpp)

TARGET_LIB=libWebSockets
LINKED_LIBS=libString libUtils libIOInterface libJSON
TAGS_FILE=dev_tools_libraries_libWebSockets-c++.tags

MODE=CPP

USE_JSON=YES
USE_WEB_SOCKET_CPP=YES

include ../makefiles_libaries.include
