SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libThreadComms libUtils libIOInterface 

EXECUTABLE=publisherSpeed
MODE=CPP
CPP_TAGS_FILE=dev_tools_binaries-publisher-speed-c++.tags
USE_JSON=YES

include ../../../../makefile.include
