EXPORT_INCLUDES=$(shell echo *.h)
SOURCES=$(shell echo *.cpp)

MODE=CPP
TAGS_FILE=math_fit_c++.tags

LINKED_LIBS=libUtils \
            libIOInterface


# REQUIRED FOR tokenizer

USE_BOOST=YES

include ../makefile.libMath.include
