LINKED_LIBS= libUtils  \
			 libIOInterface \
			 libMath \
			 libTest

BUILD_TIME_TESTS=fit
CPP_TAGS_FILE=dev_tools_tesst_math-c++.tags
MODE=CPP
TOOL_CHAIN=TRAVIS

USE_GSL=YES

include ../makefile_tests.include
