LINKED_LIBS= libUtils  \
			 libIOInterface \
			 libMath \
			 libTest \
			 libThread

BUILD_TIME_TESTS=fit
CPP_TAGS_FILE=dev_tools_tesst_math-c++.tags
MODE=CPP

USE_GSL=YES
USE_BOOST=YES

NO_INTEL=YES

include ../makefile_tests.include
