EXPORT_INCLUDES=$(shell echo *.h *.hpp)
SOURCES=$(shell echo *.cpp)

TARGET_LIB=libIOInterface
CPP_TAGS_FILE=libIOInterface-c++.tags

# We need the utils headers
ADDITIONAL_INCLUDE_FLAGS=-I$(DEV_TOOLS_DIR)/CPP/Libraries/libUtils/

include ../makefiles_libaries.include
