LINKED_LIBS= libCEF \
             libIOInterface\
             libUtils  \
			 libTest

BUILD_TIME_TESTS=jsObject
CPP_TAGS_FILE=dev_tools_cpp_tests_cef-c++.tags

USE_CEF=YES
USE_GTK=YES

TEST_LINK_CEF_RESOURCES=YES

.TEST_SETUP: test_sym_link

include ../makefile_tests.include
