EXPORT_INCLUDES=$(shell echo *.h *.hpp)

TARGET_LIB=libThreadComms
LINKED_LIBS=libString libUtils libIOInterface libJSON
TAGS_FILE=dev_tools_libraries_libThreadComms-c++.tags

MODE=CPP

USE_BOOST=YES

include ../makefiles_libaries.include
