EXPORT_INCLUDES=$(shell echo *.h *.hpp)
SOURCES=$(shell echo *.cpp)

TARGET_LIB=libJSON
LINKED_LIBS=libString libUtils libIOInterface
TAGS_FILE=dev_tools_libraries_libJSOn-c++.tags

MODE=CPP

USE_JSON=YES

include ../makefiles_libaries.include
