MAKE_DIRS= libIOInterface\
		   libUtils \
		   libString \
		   libJSON \
		   libTest \
		   libMath  \
		   libPlot   \
		   libScreen \
		   libMeta \
		   libCommands \
           libThreadComms\
		   libWebSockets 

MODE=CPP

include ../../../makefile.include
