MAKE_DIRS= libIOInterface\
		   libUtils \
		   libString \
		   libTest \
		   libMath  \
		   libPlot   \
		   libScreen \
		   libMeta \
		   libCommands

MODE=CPP

include ../../../makefile.include
