EXPORT_INCLUDES=$(shell echo *.h )
SOURCES=$(shell echo *.cpp)

TARGET_LIB=libPlot

LINKED_LIBS=libMath
USE_PLPLOT=YES

MODE=CPP
TAGS_FILE=utilities_Plot_c++.tags

NO_TRAVIS=YES


include ../../../../makefile.include
