EXPORT_INCLUDES=$(shell echo *.h )
SOURCES=$(shell echo *.cpp)

TARGET_LIB=libGTK

LINKED_LIBS=libUtils libIOInterface
USE_GTK=YES

MODE=CPP
TAGS_FILE=DEV_TOOLS_GTK_c++.tags


include ../../../../makefile.include
