MAKE_DIRS= libLog \
           libIO\
           libBinary \
           libCSV\
           libOS\
           libTime\
           libMisc \
		   libRegex \
		   libSearch


include ../makefiles_libaries.include
