LINKED_LIBS= libCommands \
             libMeta \
             libIOInterface\
             libUtils\
			 libTest

BUILD_TIME_TESTS=commands
CPP_TAGS_FILE=dev_tools_tesst_set-c++.tags
MODE=CPP

include ../makefile_tests.include
