LINKED_LIBS= libCommands \
             libMeta \
             libString \
             libIOInterface\
             libUtils\
			 libTest

BUILD_TIME_TESTS=commands
CPP_TAGS_FILE=dev_tools_tesst_set-c++.tags
MODE=CPP
BOOST_MODULES+=regex

include ../makefile_tests.include
