LINKED_LIBS= libScreen \
             libUtils\
			 libIOInterface\
			 libTest

BUILD_TIME_TESTS= screen 
CPP_TAGS_FILE=DEVTOOLS_TESTS_SCREEN-c++.tags

CORE_SIZE=unlimited

MODE=CPP

EXTERNAL_LIBS=-lncurses


include ../makefile_tests.include
