LINKED_LIBS= libJSON \
             libIOInterface\
             libUtils\
			 libTest

BUILD_TIME_TESTS=json json_gen 
CPP_TAGS_FILE=dev_tools_cpp_tests_jsob-c++.tags
MODE=CPP

USE_JSON=YES

include ../makefile_tests.include
